# ###########################################################################
#
#  CLOUDERA APPLIED MACHINE LEARNING PROTOTYPE (AMP)
#  (C) Cloudera, Inc. 2024
#  All rights reserved.
#
#  Applicable Open Source License: Apache 2.0
#
#  NOTE: Cloudera open source products are modular software products
#  made up of hundreds of individual components, each of which was
#  individually copyrighted.  Each Cloudera open source product is a
#  collective work under U.S. Copyright Law. Your license to use the
#  collective work is as provided in your written agreement with
#  Cloudera.  Used apart from the collective work, this file is
#  licensed for your use pursuant to the open source license
#  identified above.
#
#  This code is provided to you pursuant a written agreement with
#  (i) Cloudera, Inc. or (ii) a third-party authorized to distribute
#  this code. If you do not have a written agreement with Cloudera nor
#  with an authorized and properly licensed third party, you do not
#  have any rights to access nor to use this code.
#
#  Absent a written agreement with Cloudera, Inc. (“Cloudera”) to the
#  contrary, A) CLOUDERA PROVIDES THIS CODE TO YOU WITHOUT WARRANTIES OF ANY
#  KIND; (B) CLOUDERA DISCLAIMS ANY AND ALL EXPRESS AND IMPLIED
#  WARRANTIES WITH RESPECT TO THIS CODE, INCLUDING BUT NOT LIMITED TO
#  IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND
#  FITNESS FOR A PARTICULAR PURPOSE; (C) CLOUDERA IS NOT LIABLE TO YOU,
#  AND WILL NOT DEFEND, INDEMNIFY, NOR HOLD YOU HARMLESS FOR ANY CLAIMS
#  ARISING FROM OR RELATED TO THE CODE; AND (D)WITH RESPECT TO YOUR EXERCISE
#  OF ANY RIGHTS GRANTED TO YOU FOR THE CODE, CLOUDERA IS NOT LIABLE FOR ANY
#  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE OR
#  CONSEQUENTIAL DAMAGES INCLUDING, BUT NOT LIMITED TO, DAMAGES
#  RELATED TO LOST REVENUE, LOST PROFITS, LOSS OF INCOME, LOSS OF
#  BUSINESS ADVANTAGE OR UNAVAILABILITY, OR LOSS OR CORRUPTION OF
#  DATA.
#
# ###########################################################################

"""Prompts for use by PromptBrew."""

from enum import Enum

DIMENSION_DEF = """A dimension will contain categorical dimension values \
(attributes) that are qualitative and subjective to the user. This \
means there is no right answer for selecting a dimension \
value. The user should be able to select any dimension value \
depending on their preference. The dimensions must not \
be an evaluation of how good the writing is. All responses \
are assumed to be the best writing generated by you."""

DIMENSION_CONCLUSION = """Even though I encourage you to \
use some of these examples if best fitting, I highly \
recommend that I also get unique and orthogonal \
dimensions."""

NOMINAL_DIMENSION_DEF = (
    DIMENSION_DEF
    + """A nominal dimension \
will contain dimension values that do not have a particular \
order and are up to the user’s selection."""
    + DIMENSION_CONCLUSION
)
NOM_GEN_PROMPT = (
    NOMINAL_DIMENSION_DEF
    + """list \
{cat_num} nominal dimensions and associated \
{val_num} possible values on which we can \
categorize and assess the content for the \
prompt: {prompt}
####
You MUST answer in the following JSON object format, wrapped
in curly braces. Replace all strings
with <...>. There must be cat_num
items in the JSON object:
{{
"<dimension name #1>":[<{val_num} 
values for this dimension>],
...,
“<dimension name #{cat_num}>” :
[<{val_num} values for this dimension>]
}}"""
)

ORDINAL_DIMENSION_DEF = (
    DIMENSION_DEF
    + """An ordinal dimension will contain \
dimension values measured in an order (least, less, neutral, \
more, most). The type of dimensions I want are ones that \
are of a single key property that the user may want more \
of or less of depending on their preference."""
    + DIMENSION_CONCLUSION
)

ORD_GEN_PROMPT = (
    ORDINAL_DIMENSION_DEF
    + """list {cat_num} ordinal dimensions on which
we can assess the outcome for the
prompt: {prompt} to what extent represents the dimensions
####
answer in the following JSON format:
{{
"<dimension name>": ["least",
"less", "neutral", "more", "most"]
}}"""
)

SIMPLE_PROMPT_GEN_EXAMPLES = """
####

Requirements: 
Engaging: most
Images: more
Elaborate: more

Input Variables:
document_type - type of document to be generated
text - the reference text to be used

Prompt: "Create a {{document_type}} based on the text below:

{{text}}"

Refined prompt with instructions: "You have to write an engaging {{document_type}} based on the \
provided basic points that need to be covered. You can ask for \
images to be included in different parts of the text, and will \
add them later by a human. Elaborate on the pointers to provide \
more context. Here is what you need to cover:

{{text}}

Result: "

####

Requirements:
Accuracy: most
Originality: most

Input Variables:
text - the text to summarize

Prompt: "Create a summary of the given text in the voice of Harry Potter.

{{text}}"

Refined prompt with instructions: "Read the text carefully \
and create a concise summary of the main points. Make sure \
to include enough detail so that the summary accurately \
reflects the content of the text. Your summary should be \
at least 300 words. Once you have finished, present the \
summary in the form of a paragraph or multiple paragraphs. \
Make sure to include the key points that were discussed in \
the text. IMPORTANT - Make sure to use your own words and avoid using \
direct quotes from the text. 

Text: {{text}}

Summary in the voice of Harry Potter: "

####

Requirements:
Nutrition: most
Variety: more
Taste: more

Input Variables:
family_details - numerical details of the family
dietary_restrictions - dietary restrictions, if any
cuisine_preferences - preference of cuisine, if any

Prompt: "Create a 7 day meal plan using the dietary restrictions given \
below with given 
DIETARY RESTRICTIONS: {{dietary_restrictions}}"

Refined prompt with instructions: "Create a 7 day meal plan using the \
dietary restrictions given below.
FAMILY_DETAILS: {{family_details}}
DIETARY RESTRICTIONS: {{dietary_restrictions}}
CUISINE PREFERENCES: {{cuisine_preferences}}
If any details are missing, make common sense assumptions.
Meal Plan: "
"""

COT_PROMPT_GEN_EXAMPLES = """
####

Requirements:
Engaging: most
Images: more
Elaborate: more

Input Variables:
document_type - type of document to be generated
text - the reference text to be used

Prompt: "Create a {{document_type}} based on the text below:

{{text}}"

Refined prompt with instructions: "You have to write an engaging {{document_type}} based on the \
provided basic points that need to be covered. You can ask for \
images to be included in different parts of the text, and will \
add them later by a human. Elaborate on the pointers to provide \
more context. Here is what you need to cover:

{{text}}

Result: Let's think step by step. "

####

Requirements:
Accuracy: most
Originality: most

Input Variables:
text - the text to summarize

Prompt: "Create a summary of the given text in the voice of Harry Potter.

{{text}}"

Refined prompt with instructions: "Read the text carefully \
and create a concise summary of the main points. Make sure \
to include enough detail so that the summary accurately \
reflects the content of the text. Your summary should be \
at least 300 words. Once you have finished, present the \
summary in the form of a paragraph or multiple paragraphs. \
Make sure to include the key points that were discussed in \
the text. IMPORTANT - Make sure to use your own words and avoid using \
direct quotes from the text.

Text: {{text}}

Summary in the voice of Harry Potter: Let's think step by step. "

####

Requirements:
Nutrition: most
Variety: more
Taste: more

Input Variables:
family_details - numerical details of the family
dietary_restrictions - dietary restrictions, if any
cuisine_preferences - preference of cuisine, if any

Prompt: "Create a 7 day meal plan using the dietary restrictions given \
below with given
DIETARY RESTRICTIONS: {{dietary_restrictions}}"

Refined prompt with instructions: "Create a 7 day meal plan using the \
dietary restrictions given below.
FAMILY_DETAILS: {{family_details}}
DIETARY RESTRICTIONS: {{dietary_restrictions}}
CUISINE PREFERENCES: {{cuisine_preferences}}
If any details are missing, make common sense assumptions.
Meal Plan: Let's think step by step. "
"""

FEW_SHOT_COT_PROMPT_GEN_EXAMPLES = """
####

Requirements:
Engaging: most
Images: more
Elaborate: more

Input Variables:
document_type - type of document to be generated
text - the reference text to be used

Prompt: "Create a {{document_type}} based on the text below:

{{text}}"

Refined prompt with instructions: "You have to write an engaging {{document_type}} based on the \
provided basic points that need to be covered. You can ask for \
images to be included in different parts of the text, and will \
add them later by a human. Elaborate on the pointers to provide \
more context. Here is what you need to cover:

====
Text: 
* AI and regulation of AI
* Importance of regulation
* Fast pace of development in the industry

Result: Let's think step by step. 
# Title: Navigating the Future: AI Regulation in an Era of Rapid Development

In the fast-evolving landscape of artificial intelligence (AI), where breakthroughs seem to happen almost daily, the need for clear and effective regulation has become more urgent than ever. As we stand at the intersection of innovation and ethics, understanding the dynamics of AI regulation is crucial for shaping a responsible and equitable future.

**The Fast Pace of AI Development**
AI technology is advancing at a breathtaking pace, revolutionizing industries from healthcare to finance, and from transportation to entertainment. Every year brings new capabilities and applications, pushing the boundaries of what was previously thought possible. From self-driving cars to personalized medicine, AI promises to transform our world in profound ways.

However, this rapid progress also raises significant questions and challenges. As AI systems become more complex and integrated into everyday life, concerns about privacy, bias, accountability, and safety naturally arise. These technologies hold immense potential, but they also come with potential risks that need careful management.

**The Importance of Regulation**
Effective regulation plays a pivotal role in harnessing the benefits of AI while mitigating its risks. Regulation provides a framework to ensure that AI systems are developed and deployed responsibly. It sets standards for data privacy, algorithmic transparency, accountability mechanisms, and ensures that AI technologies are used in ways that align with societal values and ethical principles.

Without regulation, there is a risk that AI deployment could outpace our ability to understand and manage its implications. Clear guidelines and policies help to foster trust among users, businesses, and policymakers, enabling innovation to flourish in a sustainable manner.

**AI and the Need for Ethical Considerations**
Ethical considerations are at the heart of AI regulation. As AI algorithms make decisions that impact individuals and societies, it becomes crucial to address questions of fairness, equity, and justice. Issues such as algorithmic bias, discrimination, and the ethical use of data underscore the importance of implementing robust regulatory frameworks.

Moreover, international cooperation is essential in addressing global challenges posed by AI. Harmonizing standards and regulations across borders ensures consistency and facilitates innovation on a global scale while safeguarding against potential abuses of AI technology.

**Looking Ahead: Building a Responsible Future**
As we look ahead, the conversation around AI regulation will only become more critical. It requires collaboration among governments, industry leaders, researchers, and civil society to strike the right balance between innovation and protection. Educating the public about AI, its capabilities, and its implications is also crucial in shaping informed policies and decisions.

In conclusion, while AI presents unprecedented opportunities for progress and innovation, navigating its development requires careful consideration of ethical, legal, and societal implications. By establishing thoughtful regulations, we can ensure that AI technologies serve humanity’s best interests, driving positive change and creating a future where innovation thrives responsibly.

====
Text: Features of the brand new smartwatch:
* Stylish and lightweight design, perfect for everyday wear.
* High-resolution touchscreen display for clear visibility.
* Tracks fitness metrics like steps, distance, calories burned, and heart rate.
* Built-in GPS for accurate outdoor activity tracking.
* Notifications for calls, messages, and app alerts directly on your wrist.
* Long-lasting battery life with quick charging capability.
* Water-resistant for worry-free use during workouts and in rain.
* Compatible with iOS and Android smartphones for seamless connectivity.

Result: Let's think step by step. 
# Discover the Ultimate Companion: The All-New Smartwatch

Experience a new era of wearable technology with our brand new Smartwatch, meticulously crafted to elevate your daily life with style, functionality, and seamless connectivity.

**Stylish and Lightweight Design**
Embrace elegance with a sleek, lightweight design that blends effortlessly with any outfit, whether you're at the gym, in the office, or out for a night on the town.

**High-Resolution Touchscreen Display**
Navigate with clarity on a high-resolution touchscreen display that ensures crystal-clear visibility in any environment, from bright sunlight to dimly lit spaces.

**Advanced Fitness Tracking**
Achieve your fitness goals with comprehensive tracking of steps, distance, calories burned, and real-time heart rate monitoring. Stay motivated and informed about your health metrics at a glance.

**Built-in GPS for Outdoor Enthusiasts**
Explore confidently with built-in GPS functionality that accurately tracks your routes and distances during outdoor activities like running, cycling, and hiking.

**Stay Connected with Notifications**
Keep in touch without missing a beat - receive notifications for calls, messages, and app alerts directly on your wrist, so you can stay connected while on the move.

**Long-Lasting Battery Life**
Power through your day with ease thanks to a long-lasting battery that keeps up with your busy lifestyle. Quick charging capabilities ensure you're never without your essential companion for long.

**Designed for All Environments**
From intense workouts to unexpected showers, our Smartwatch is water-resistant, offering worry-free durability in all weather conditions.

**Seamless Compatibility**
Enjoy effortless connectivity with both iOS and Android smartphones, allowing you to sync data, receive updates, and maximize the full potential of your smartwatch experience.

**Embrace the Future Today**
Elevate every moment with the all-new Smartwatch, where style meets functionality in perfect harmony. Whether you're prioritizing fitness, staying connected, or simply enhancing your daily routine, this smart companion is designed to exceed your expectations.


====
Text: {{text}}

Result: Let's think step by step. "

####

Requirements:
Accuracy: most
Originality: most

Input Variables:
text - the text to summarize

Prompt: "Create a summary of the given text in the voice of Harry Potter.

{{text}}"

Refined prompt with instructions: "Read the text carefully \
and create a concise summary of the main points. Make sure \
to include enough detail so that the summary accurately \
reflects the content of the text. Your summary should be \
at least 300 words. Once you have finished, present the \
summary in the form of a paragraph or multiple paragraphs. \
Make sure to include the key points that were discussed in \
the text. IMPORTANT - Make sure to use your own words and avoid using \
direct quotes from the text.

====
Text: **Minutes of the Marketing Strategy Meeting**

**Topic: Enhancing Digital Presence and Customer Engagement at Hogwarts School of Witchcraft and Wizardry**

In today's marketing strategy meeting, our focus was on optimizing our digital presence and enhancing customer engagement strategies. The meeting commenced with a review of current marketing initiatives, including social media campaigns and website analytics. Key metrics such as engagement rates, click-through rates, and conversion rates were discussed to gauge the effectiveness of our current strategies.

The team brainstormed innovative approaches to increase brand visibility across digital platforms. Ideas included launching targeted email marketing campaigns, leveraging influencer partnerships to reach new demographics, and optimizing SEO strategies to improve organic search rankings. Emphasis was placed on creating personalized customer experiences through tailored content and interactive features on our website.

Furthermore, the meeting highlighted the importance of data-driven decision-making. Plans were outlined to implement advanced analytics tools to gain deeper insights into customer behavior and preferences. This data will inform future marketing campaigns and strategic initiatives aimed at enhancing customer satisfaction and loyalty.

In conclusion, the team agreed on action items and timelines for the implementation of new strategies. Follow-up meetings were scheduled to monitor progress and make necessary adjustments. The collective goal remains to elevate our digital presence and strengthen customer engagement, ensuring continued growth and success in the competitive market landscape.

Summary in the voice of Harry Potter: Let's think step by step. In today's marketing strategy meeting at Hogwarts School of Witchcraft and Wizardry, our focus was on optimizing our digital presence and enchanting customer engagement strategies across magical platforms. The session began with a thorough review of our current marketing charms, including analyses of spellbinding social media campaigns and enchanted website analytics. Key magical metrics such as engagement rates, click-through rates, and conversion rates were carefully examined to assess the effectiveness of our current incantations.

The team conjured innovative approaches to increase brand visibility across magical realms. Ideas floated included casting targeted owl-delivered messages, harnessing the influence of magical creatures to attract new wizarding demographics, and refining our enchantments to improve organic search rankings. A strong emphasis was placed on creating personalized customer experiences through tailored potions and interactive features on our enchanted parchment scrolls.

Furthermore, the meeting emphasized the importance of prophecy-driven decision-making. Plans were sketched to implement advanced scrying crystals to gain deeper insights into customer behaviors and preferences. This mystical data will serve as the foundation for future marketing spells and strategic initiatives aimed at enhancing customer satisfaction and loyalty among Hogwarts students and magical beings alike.

In conclusion, the enchanted team unanimously agreed on spell scrolls detailing actionable charms and set timelines for the implementation of these new magical strategies. Follow-up meetings were scheduled to monitor the ripple effects of our spells, evaluate results, and make necessary adjustments as needed. The overarching objective remains steadfast: to elevate our digital presence, strengthen customer engagement through enchanting experiences, and ensure continued growth and success in the competitive magical marketplace of Hogwarts.

====
Text: **Record-breaking Sales for Fireworks Extravaganza: A Success Story**

In a spectacular triumph of innovation and consumer appeal, Fireworks Extravaganza has ignited the market with their latest product, the Everlasting Celebration Fireworks. Launched at a highly anticipated event in downtown New York, these state-of-the-art fireworks have captured the imagination and wallets of customers far and wide.

The Everlasting Celebration Fireworks, engineered by renowned pyrotechnic experts, not only dazzle spectators with vibrant colors and intricate patterns but also boast a groundbreaking feature: the ability to regenerate and burst anew throughout an entire evening of festivities. This unique capability has made them an instant hit at major events and celebrations across the country.

"We are thrilled with the phenomenal response to our Everlasting Celebration Fireworks," stated John Smith, CEO of Fireworks Extravaganza. "The innovative design and exceptional performance have resonated deeply with our customers. They bring an unparalleled level of excitement and joy to any occasion."

The success of the Everlasting Celebration Fireworks can be attributed to their blend of cutting-edge technology and crowd-pleasing appeal. Event organizers and consumers alike have been captivated by the fireworks' ability to enhance special moments with their dynamic displays and continuous bursts of light and color.

Industry analysts have hailed Fireworks Extravaganza's achievement as a testament to their understanding of market trends and consumer preferences. "The company's commitment to innovation has clearly paid off," remarked Sarah Johnson, a market research expert. "By combining advanced pyrotechnic engineering with a focus on user experience, Fireworks Extravaganza has carved out a niche in the competitive fireworks market."

Looking forward, Fireworks Extravaganza plans to expand distribution of the Everlasting Celebration Fireworks to major cities nationwide, ensuring that more consumers can experience the magic of these exceptional fireworks. With such resounding success, Fireworks Extravaganza continues to set the standard for excellence in the pyrotechnics industry, delighting audiences and creating unforgettable moments one burst at a time.

Summary in the voice of Harry Potter: Let's think step by step. **Enchanted Success at Diagon Alley: Fireworks Enchantment Ltd. Celebrates Record Launch**

In a dazzling display of magical innovation, Fireworks Enchantment Ltd. has captivated the wizarding world with their latest creation, the Everlasting Enchantment Fireworks. Launched at a prestigious gala in Diagon Alley, these enchanted fireworks have quickly become a sensation among witches and wizards.

Crafted by renowned pyrotechnic expert John Smith, the Everlasting Enchantment Fireworks not only dazzle with vibrant colors and intricate patterns but also boast a groundbreaking feature: the ability to regenerate and burst anew throughout an entire night of celebrations. This magical capability has made them indispensable for every wizarding event, from Hogwarts reunions to magical weddings.

"We are thrilled by the overwhelming response to our Everlasting Enchantment Fireworks," exclaimed John Smith, CEO of Fireworks Enchantment Ltd. "The magical designs and exceptional performance have resonated deeply with our magical community, bringing unparalleled joy and excitement to every celebration."

The success of the Everlasting Enchantment Fireworks underscores their blend of magical craftsmanship and irresistible charm. Event organizers and magical enthusiasts alike have been enchanted by the fireworks' ability to elevate special occasions with their dynamic displays and continuous bursts of magic and color.

Market experts within the wizarding community have praised Fireworks Enchantment Ltd. for their visionary approach and understanding of magical trends. "John Smith's leadership and innovation have set a new standard in pyrotechnics," remarked Professor Flitwick, a respected Charms expert and industry observer. "His ability to blend traditional fireworks with magical enhancements has enchanted a loyal customer base."

Looking forward, Fireworks Enchantment Ltd. plans to expand distribution of the Everlasting Enchantment Fireworks to magical communities worldwide, ensuring that witches and wizards everywhere can experience the wonder of these exceptional fireworks. With such resounding success, Fireworks Enchantment Ltd. continues to lead the way in enchantment, delighting audiences and creating unforgettable magical moments with every burst.
====

Text: {{text}}

Summary in the voice of Harry Potter: Let's think step by step. "
"""

EXPERT_PROMPT_GEN_EXAMPLES = """
####

Requirements: 
Engaging: most
Images: more
Elaborate: more

Input Variables:
document_type - type of document to be generated
text - the reference text to be used

Prompt: "Create a {{document_type}} based on the text below:

{{text}}"

Refined prompt with instructions: "You are an expert at \
content creation, especially written. You have to write \
an engaging {{document_type}} based on the provided basic \
points that need to be covered. You can ask for \
images to be included in different parts of the text, and will \
add them later by a human. Elaborate on the pointers to provide \
more context. Here is what you need to cover:

{{text}}

Result: "

####

Requirements:
Accuracy: most
Originality: most

Input Variables:
text - the text to summarize

Prompt: "Create a summary of the given text in the voice of Harry Potter.

{{text}}"

Refined prompt with instructions: "You are an expert at \
summarizing and rewriting written content. You are to go through \
the text carefully and create a concise summary of \
the main points. Make sure to include enough detail \
so that the summary accurately reflects the content \
of the text. Your summary should be at least 300 words. \
Once you have finished, present the summary in the \
form of a paragraph or multiple paragraphs. \
Make sure to include the key points that were discussed in \
the text. IMPORTANT - Make sure to use your own words \
and avoid using direct quotes from the text. 

Text: {{text}}

Summary in the voice of Harry Potter: "

####

Requirements:
Nutrition: most
Variety: more
Taste: more

Input Variables:
family_details - numerical details of the family
dietary_restrictions - dietary restrictions, if any
cuisine_preferences - preference of cuisine, if any

Prompt: "Create a 7 day meal plan using the dietary restrictions given \
below with given 
DIETARY RESTRICTIONS: {{dietary_restrictions}}"

Refined prompt with instructions: " You are an expert dietician. \
You are to go through the information below and create a 7 day meal \
plan using the dietary restrictions and preferences stated.
FAMILY_DETAILS: {{family_details}}
DIETARY RESTRICTIONS: {{dietary_restrictions}}
CUISINE PREFERENCES: {{cuisine_preferences}}
If any details are missing, make common sense assumptions.
Meal Plan: "
"""

GEN_EXAMPLES = {
    "SIMPLE": SIMPLE_PROMPT_GEN_EXAMPLES,
    "ZERO_SHOT_CHAIN_OF_THOUGHT": COT_PROMPT_GEN_EXAMPLES,
    "FEW_SHOT_CHAIN_OF_THOUGHT": FEW_SHOT_COT_PROMPT_GEN_EXAMPLES,
    "ASSUMED_EXPERTISE": EXPERT_PROMPT_GEN_EXAMPLES,
}

PromptStyle = Enum(
    "PromptStyle",
    # use the keys as both names and values, otherwise values would be ints
    names=zip(GEN_EXAMPLES.keys(), GEN_EXAMPLES.keys()),
    type=str,
)


PROMPT_GEN_PROMPT_TEMPLATE = """Step 1:
Go through the given prompt, requirements of the output \
and a list of input variables. Keep a note of all the \
requirements and input variables to follow. DO NOT FORGET \
ABOUT ANY OF THE INPUT VARIABLES.

Step 2:
Based on the task in the prompt, return a refined prompt \
which also has a small set of instructions to follow \
which addresses the requirements along with the input \
variables. The prompt should be as instructive as possible \
and should be second person voice. Assume that the input variables \
will be substituted into the prompt later and should be in \
double curly braces in the prompts. Please include all the \
input variables mentioned in `Step 1` in the refined \
prompt with instructions. You can add step-wise \
instructions in the refined prompt if needed. If there \
are examples in the prompts below, add the same number \
of examples in the refined prompt. After mentioning the \
examples, do add a placeholder for the input variables \
and the result placeholder.

{examples}

####

Requirements: {requirements}

Input Variables: {input_variables}

Prompt: {prompt}

Refined prompt with instructions:
"""
